# Generated by Django 2.1.7 on 2019-03-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0003_auto_20190304_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
